name: Build Bardo Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Android APK with Buildozer
        uses: ArtemSuldin/buildozer-action@v1
        with:
          command: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Bardo-Android-APK
          path: bin/*.apk